README.md
=> Soup up README (Closes #12)

README.md
=> README: adding 1 more image

screw_maker.py
=> Misc. typo and whitespace fixes

FastenerBase.py
Dirty fix, but working just fine with 18.1
=> Fix for issue #45 and #46.

README.md
Added License section  
Split the Installation section  
Refining markdown  
Typo fixes
=> README: refinements

FastenersCmd.py, Icons/DIN7984.svg, ScrewMaker.py, screw_maker.py
add DIN 7984 screws
“Zylinderschrauben mit Innensechskant, niedriger Kopf, ohne Schlüsselführung”
=> DIN 7984 screws

CountersunkHoles.py, FSChangeParams.py, FastenerBase.py, FastenersCmd.py, ScrewMaker.py
ref: https://lgtm.com/projects/g/shaise/FreeCAD_FastenersWB/?mode=tree&ruleFocus=7900090
=> LGTM: fix 'Testing equality to None' alert

Icons/DIN6912.svg
New icon is more realistic (hex-size) and more different to DIN 7984
=> Better icon for DIN 6912

FastenerBase.py, screw_maker.py
Started to translate comments to english for clarity and future developers looking at the code
=> Translate comments from DE to EN

FSChangeParams.py, FastenerBase.py, PEMInserts.py
This PR fixes the BOM generator so that it includes heat set inserts added in PR #104
=> include heat set inserts in bom

FSChangeParams.py, FSNuts.py, FSScrewCalc.py, FastenerBase.py, FastenersCmd.py, InitGui.py, PEMInserts.py, ScrewMaker.py, screw_maker.py
Reformat code to Python's standart 4 spaces as indentation
=> Fix indentations

FSChangeParams.py, FSNuts.py, FSScrewCalc.py, FastenerBase.py, FastenersCmd.py, InitGui.py, PEMInserts.py, ScrewMaker.py, screw_maker.py
Reverts shaise/FreeCAD_FastenersWB#123
=> Revert "Fix indentations"

package.xml
Corrected the branch (this repo uses "master" as its primary branch) and added a direct link to the README.md HTML rendering.
=> Tweak package.xml

CONTRIBUTING.md
Fix markdown, typo, and some reformatting  
Preview: https://github.com/luzpaz/FreeCAD_FastenersWB/blob/CONTRIBUTING/CONTRIBUTING.md#additional-changes
=> CONTRIBUTING.md: tweaks

FastenerBase.py
This PR fixes some count issues in FSMakeBomCommand. It has been tested on a file with reasonably complex nesting structures (see largest file in the attached ZIP).
fixes https://github.com/shaise/FreeCAD_FastenersWB/issues/60
In the attached ZIP are 3 FCStd files. Each has an 'old' BOM (created with the current code) and a 'new' BOM created with the modified code.
[fasteners_array_link_BOM_test.zip](https://github.com/shaise/FreeCAD_FastenersWB/files/9460827/fasteners_array_link_BOM_test.zip)
=> FS: Fix count issues in FSMakeBomCommand

FsFunctions/FSmakeTSlotNut.py
DIN508 finished, now in next days I'll try to extend the options available creating a new category.
Completing #207
=> Add holes with no thread in DIN508 T-Slot nut

FastenerBase.py
If no one is against, I propose such a solution.
=> FastenerBase.py separate commands in code

FsFunctions/FSmakeWoodScrew.py
+ Formulas are replaced with understandable ones.
+ More understandable variable names.
+ Contour creation code is fixed.
+ Explanations to calculations added.
+ More tidy code formatting.
=> GOST 1144 (Wood screws) code refactoring

FastenerBase.py
Co-Authored-By: Shai Seger <5813568+shaise@users.noreply.github.com>
#244
=> Fix toolbars names from #244 issue

README.md
LGTM will be shut down this week.
@shaise if you are interested in replacing the code-scanning functionality, you can look into [GitHub code scanning](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/setting-up-code-scanning-for-a-repository).
=> Remove LGTM badges

FsFunctions/FSmakePEMStandoff.py
[https://forum.freecad.org/viewtopic.php?p=664756#p664756](https://forum.freecad.org/viewtopic.php?p=664756#p664756)
=> Fix hex cut for PEM standoffs

package.xml
=> Fix package.xml typo

FastenersCmd.py
Sorted by Group Type, then Alphabet and then Number 
ASME
DIN
GN
GOST
ISO
NFE
SAE
This should help to find things, and it makes it a bit cleaner.
=> FSScrewCommandTable sorting

FsFunctions/FSmakeTSlot.py
see issue https://github.com/shaise/FreeCAD_FastenersWB/issues/372
=> “better” shape for nut

FastenerBase.py, FastenersCmd.py
=> Fix attempt of reading unexistent parameters

FsFunctions/FSmakeTSlot.py
Cut was done before it was needed. 
Not sure why I moved the command there \_-\_
Fix #375
=> Fix cut on GN505 fasteners

FSChangeParams.py
as per https://github.com/shaise/FreeCAD_FastenersWB/issues/427#issuecomment-2711896596
=> Parameters dialog: add tooltip desciption for each type
