screw_maker.py

Came accross the following error with FreeCAD 0.18 and python 3.6.7.
```
Traceback (most recent call last):
File "/home/chris/.FreeCAD/Mod/fasteners/FastenersCmd.py", line 121, in execute
s = screwMaker.createFastener(fp.type, d, l, threadType, True)
File "/home/chris/.FreeCAD/Mod/fasteners/ScrewMaker.py", line 264, in createFastener
return self.createScrew(type, diam, len, threadType, shapeOnly)
File "/home/chris/.FreeCAD/Mod/fasteners/screw_maker.py", line 2204, in createScrew
screw = self.makeIso4762(ST_text, ND_text,l)
File "/home/chris/.FreeCAD/Mod/fasteners/screw_maker.py", line 3780, in makeIso4762
rthread = self.makeShellthread(dia, P, halfturns, True, offSet)
File "/home/chris/.FreeCAD/Mod/fasteners/screw_maker.py", line 4098, in makeShellthread
for i in range(rotations-2, …
```

rotations should be a int

---

FastenerBase.py

Convert keys() return value to list to make sure that it is not a
reference (e.g. DictView). Fixes:
RuntimeError: dictionary changed size during iteration

Do not delete dict items while iterating over keys

---

FSprefs.ui

per [this forum post](https://forum.freecadweb.org/viewtopic.php?f=8&t=11429&start=280#p528028)
For users working on UI improvements, grouping all the 'add fastener' buttons in one toolbar tends to cause problems. 
We already have the ability to split commands to multiple toolbars via a preferences setting. This PR makes the 'Separate Toolbars' option the default for new installations.

group fastenersWB commands as seperate toolbars by default

---

FSNuts.py
FastenerBase.py
FastenersCmd.py
PEMInserts.py

possibly/partially addresses #90 
currently, attached fasteners produce an error message every time they are recomputed
e.g.: `<App> GeoFeatureGroupExtension.cpp(577): t1#Screw.baseObject(links to t1#Body) is out of scope:t1#Part vs. <global>
`
The fix is to use `PropertyLinkSubGlobal` instead of `PropertyLinkSub`. This PR also updates fasteners in existing documents. (The error msg shows up one final time during the update process)

fix link out-of-scope warning for attached fasteners

---

Icons/IUTHeatInsert.svg
PEMInserts.py

I modified the PEM Press Nut code to make the IUT functions and added it onto the end of `PEMInserts.py`. The added fastener class references a PEM catalogue for dimensions and specs. 
[Link to PEM Catalogue, see page 6](https://www.pemnet.com/fastening_products/pdf/sidata.pdf)
If you would prefer to have me refactor into a seperate file, or change the logo, or anything else please let me know.

Add IUT[A/B/C] heatset inserts for 3D print modeling

---

screw_maker.py

to address #103 
We currently can't reliably generate modeled threads for many inch fasteners. I decided to completely rewrite `makeShellthread` to make it more robust. The rewrite ensures that the top open part of the shell it returns always has the correct circular shape, among other minor optimizations:
The new code uses more solid operations, but calculation time seems to be essentially the same.
I also ended up writing a hacky sort of unit test script to check thread generation behavior. 
I was able to use this script to confirm that the new code doesn't return OCC errors, and more reliably generate watertight solid geometry.
``` python
import FreeCAD
import FreeCADGui
def runTests():
FreeCADGui.activateWorkbench("FastenersWorkbench")
doc = FreeCAD.newDocument()
if not doc:
raise …
```

Refactor makeShellthread

---

FastenersCmd.py
screw_maker.py

Fixes some mistakes I made when I added custom sizing options to the thread-cutting tools.
Screwtap, Screwdie, and threaded rod objs now respect 3D print scaling settings.
measuring in a sketch to confirm that scaling is occurring on an M6 screwtap:

use 3D print scaling w. thread cutting tools (#101)

---

FastenerBase.py

Updated version of FSGetAttachableSelections to fix two problems:
* Face selection did not work for PD Bodies if their "Display Mode" was set to "Through".
* Face holes with two semi-circular edges received two fasteners.
Forum topics:
https://forum.freecadweb.org/viewtopic.php?p=581832#p581832
https://forum.freecadweb.org/viewtopic.php?p=582079#p582079
Issue:
https://github.com/shaise/FreeCAD_FastenersWB/issues/131

FS: fix body face selection and duplicate fasteners

---

FSprefs.ui
FastenerBase.py

Since the default menu and toolbar are quite crowded it is better to make `ScrewToolbarGroupMode=1` the default.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=8&t=67503&p=584072#p584072
Note that I have not updated package.xml.

FS: change default ScrewToolbarGroupMode

---

FastenerBase.py

- Remove ScrewTap from the BOM (as discussed in #139)
- Add ThreadedRod instead, which was missing.
This PR adds a new FSScrewStr utility function to generate the descriptive [M]\<dia>x\<len>[LH] output to avoid duplication that handles the various combination of properties we have around.
This turns descriptions such as "Screw Customx12.2 mmLH" to "Screw 6x12.2LH" (as one extreme example I spotted).
The units in the string are omitted when using custom lengths and diameters, and will follow the units as configured in freecad. For a metric system this results in more-or-less what we want.
This function should also be used to generate the descriptive labels in the tree, as I spotted at least 4 cases in my previous PR where this is done by copy-pasting and incompletely. I will probably do …

Improve BOM generation

---

FastenersCmd.py

The recently added NFE27-619 washer was not inserted in the right place in the FSAddScrewCommand and the existing order of the list was hard to understand (compare the position of the orange nuts and washer to that of their green counterparts). Note that the proposed reorganization only affects the layout of the single toolbar.

Update order in single fasteners toolbar

---

FastenersCmd.py

In case of enabled 3D Printing, if we are changing the values for screws, they are ignored on recompute until the restart of FreeCAD due to wrongly generated key which is never cleared from cache.
Solution: threadType must be always the last parameter when generating the cache key, as FastenerBase.FSCacheRemoveThreaded expects.

Fix Recompute of Screws and Nuts Threaded for 3D Printing

---

screw_maker.py

Using Part.makeLongHelix improves thread generation reliability.
Rotating the thread solid so that cylinder seams do not line up is also helpful.
see discussion in #148

Improve DIN 7998 thread generation

---

screw_maker.py

... that tried to call a function that did not exist,
breaking all hexagonal nuts (introduced in 1461d23541a9d5f7d9e7bd0da486ba4f624b5184)

Fix typo in makeIso4032

---

screw_maker.py

@berberic2 pointed out that I misread the original part drawing, and the generated nuts were too short.

Improve cap nut geometry

---

FastenersCmd.py

The translation of groups is repeated when creating the command table.
In addition, it makes the command lines very long and inconveniently readable.
I propose the following solution:
The groups are translated once before the formation of the command table. 
This should increase the readability of the table. 
And generally have a positive impact on the development.
In addition, it will reduce the size of the FSScrewCommandTable code in bytes.

Optimization of the FSScrewCommandTable.

---

FastenersCmd.py

the old behavior was to dump the length value (as string e.g.: "6mm", "3/4in") into the featurePython 'lengthCustom' property.
This mostly worked, but it would fail on length formatted like "1 3/4in".
So selecting some inch fasteners would cause the expression parser to throw a syntax error
One line fix.

FastenersCmd.py: Convert from str when assigning lengthcustom property

---

FsFunctions/FSmakeWoodScrew.py

I found that the head of the GOST 1144 screw is not built quite correctly. 
I think this also applies to the DIN 96 screw.
This pull request must fix that.
And I add rounding under screw head.

GOST 1144 head shape fix.

---

FastenersCmd.py
GrammaticalTools.py
InitGui.py

GrammaticalTools.py is a special file that contains tools for converting text into the correct form. The English language is contain limited variants of grammatical cases, so simply adding "Add" at the beginning of a line makes the following text not grammatically correct. Of course, is possible to duplicate these variants of translations in * .ts files, but this will greatly increase it. This simple and short script allows you to avoid this. At a minimum, this script removes the second capital letters. Perhaps this is a temporary solution and in the future something better will be invented. Now this is worked only for the Russian language and this will not affect to other languages ​​in any way. However, if desired, other developers or translators can add their code to this script for …

Add GrammaticalTools.py

---

TRANSLATIONS.md

The point in the path is needed to read it correctly, images didn't showed in offline md reader.

Fix relative path

---

FsFunctions/FSmakeNylocNut.py

The cutting tool was not created tall enough, causing the top section to be clipped off.

Fix Nyloc hex cut

---

CountersunkHoles.py
InitGui.py

I complete the GUI translations that are missing.
1.  3D view contextual menu 
`Fasteners` - no translation
2.  dialog of the FSFillet tool
`Default` - no translation
The context of the `translate()` function has been adjusted so that the translators have no extra work.

GUI translations

---

TranslateUtils.py

Using
`from DraftGui import translate`
has the side-effect that the draftToolBar is initialized. In the Draft working plane code I am currently working on, I check for the presence of this toolbar to trigger the grid.
It is any case better to import directly:
`from draftutils.translate import translate`

TranslateUtils.py: import translate from correct Draft file

---

CountersunkHoles.py
FastenerBase.py
FastenersCmd.py

Hi @shaise,  
Since Py3.11 the methods names __setstate__ and __getstate__ conflict with the method names added to the object class.
In [FreeCAD App: Fixe #10460](https://github.com/FreeCAD/FreeCAD/commit/83d4080fe8) they have been renamed to 'loads' and 'dumps' 
This functions are called by the FreeCAD file [src/App/PropertyPythonObject.cpp](https://github.com/FreeCAD/FreeCAD/blob/main/src/App/PropertyPythonObject.cpp)
@++;
Gauthier.

Issue #297 FastenersCmd.FSViewProviderTree not JSON serializable patch

---

CountersunkHoles.py

Closes #315
Print a deprecation warning when restoring documents that use this object.
The GUI command to add this feature to new designs is removed, but existing objects will continue to function properly

Deprecate CountersunkHoles object

---

FsFunctions/FSmakeHexHeadBolt.py

This screw was not included in the main control flow code making to raise an `NotImplementedError()`.
Fix #349

Make ASMEB18.2.1.6 reappear in 3D view

---

FSChangeParams.py
FSScrewCalc.py
FastenerBase.py

Needed to make link to FreeCAD Wiki works fine.
I asked Roy to update "Simplify" Wiki page: https://forum.freecad.org/viewtopic.php?t=85208
Related #33 #353

Fix commands' names

---

FSAliases.py

DIN961's alias was ISO8676 which itself had an alias.

Fix icon alias for DIN961

---

CountersunkHoles.py
FSChangeParams.py

Because `QtWidgets.QDialogButtonBox.StandardButtons` are already converted into `int`s in FreeCAD's `Gui::TaskDialogPython::getStandardButtons`, such conversions in workbench code aren't needed. Also this fixes compatibility with PySide6.
https://github.com/FreeCAD/FreeCAD/blob/b9bfa5c5507506e4515816414cd27f4851d00489/src/Gui/TaskView/TaskDialogPython.cpp#L736-L754

Discard unneeded int casts in getStandardButtons methods

---

FastenerBase.py

Fixes this error, reported on forum https://forum.freecad.org/viewtopic.php?t=87169:
```
Running the Python command 'Fasteners_BOM' failed: Traceback (most recent call last):
File "/home/john/.local/share/FreeCAD/Mod/fasteners/./FastenerBase.py", line 897, in Activated
method(obj, cnt)
File "/home/john/.local/share/FreeCAD/Mod/fasteners/./FastenerBase.py", line 915, in AddScrew
" Screw ") + FSScrewStr(obj)
File "/home/john/.local/share/FreeCAD/Mod/fasteners/./FastenerBase.py", line 184, in FSScrewStr
if isinstance(dia, FreeCAD.Units.Quantity):
local variable 'dia' referenced before assignment
```

Fix bug when generating BOM

---

FastenersCmd.py

adds the slot width to the autogenerated names for T-slot-nuts:
Left: Old
Right: New

add slot width to autogenerated names for T-slot-nuts

---

FsFunctions/FSmakeTSlot.py

GN505.4 is not a nut. This has to be honored when diam is calculated. This makes a difference if 3D-printer-compatibility is on.
BTW: Maybe getDia should not do 3D-printer offsets if no thread is generated?

GN505.4 is not a nut

---

FastenerBase.py
FastenersCmd.py

Currently edges from Links and Link arrays are not handled properly.
Original issue:
https://github.com/FreeCAD/FreeCAD/issues/14068
Test file (remove the .zip extension):
[Fasteners_arrays_issue.FCStd.zip](https://github.com/shaise/FreeCAD_FastenersWB/files/15394806/Fasteners_arrays_issue.FCStd.zip)
The file contains a Link array, a Link to that array, a Body and a Link to that Body.
Additionally: Currently Fasteners_Move will fail if instead of the whole fastener a circular edge of the fastener is selected. This has been solved by adding the `screwObj` argument to `FSGetAttachableSelections`.

Fix handling of edges from Links

---

FsFunctions/FSmakeHexNutSpherical.py

Avoid usage of transformGeometry to prevent upgrading edges and surfaces to b-splines

Fix generation of DIN 6330 hex nut.

---

FastenerBase.py

Fix typo leading to missing cache invalidation when changing thread generation settings.
Fixes #395

Fix Thread cache invalidation

---

FastenerBase.py

Hi,
I'm the developer for the FreeCAD Ribbon. To load all commands, all workbenches must be activated to generate a data file.
During this activation an error message is shown as a dialog and in the report view.
To avoid this dialog from showing up, I've added a few try=except statements to catch the error.
Would you be so kind to review this and merge PR in to your main branch? 
The error in the report view is:
kind regards,
Paul

Added Error handling for activating from other WB

---

FSChangeParams.py
FSScrewCalc.py
Resources/translations/fasteners.ts
Resources/translations/update_translation.sh
screw_maker.py

Hi @maxe22 did you detected other missing strings?
TODO:
Fix #418

Include missing strings to translation

---

FsFunctions/FSmakeWeldNut.py

The transformGeometry method turns all geometry into B-spline curves and surfaces. If the object is not scaled unequally transformShape should be used instead.
Forum topic:
https://forum.freecad.org/viewtopic.php?t=96751

Use transformShape instead of transformGeometry for weld nuts

---

FsFunctions/FSmakeWeldNut.py

Something went wrong at my end, sorry about that.
To preserve the effect of transformShape (see #441) the subshape should be modified and a new compound created.

Fix weld nut displacement caused by #441

---

package.xml

The icon file is not (any longer) in the Resources subdirectory.

Update icon path in package.xml

---

FSChangeParams.py

Due to Deprecation warnings already being raised in Qt6.9.0 and to maintain backwards compatibility to Qt5.x this PR allows all current supported builds to still function as expected.

Prepare for QCheckBox stateChanged -> checkStateChanged
